### ISSUE TITLE
Using ShareX to upload text means Yanius downloads a txt file instead of displaying it

### ISSUE THREAD

**Issue by Makeshift** [DerEnderKeks/Yanius#33]
Was just curious if this was intended.

If I use ShareX to upload some text from my clipboard, it correctly gives me the link, but then when going to the link it downloads a txt file instead of displaying it.  Eg. https://s.makeshift.ninja/49540Wof

This is on Windows 10 using Chrome to view the file. Gifs and images work fine.

**Comment by DerEnderKeks** [comment]
This is actually not intended but I already knew that this problem exists.This happens because of the way I mark files as "to download". The library I'm using to detect the mime type of a file can't detect text files and because of that, it's set to `application/octet-stream`. This leads to the file being downloaded.

I could fix this by determining if the file has to be downloaded using the file extension. (I can't use that for the mime type in the database as I'm using that to block file uploads when the mime type is on the blacklist)
